name: auth
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  flutter: 
    sdk: flutter
  flutter_svg: ^0.22.0
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.1
  firebase_auth_web: ^3.1.0
  firebase_core: ^1.6.0
  firebase_storage: ^10.0.3
  email_validator: ^2.0.1
  flutter_facebook_auth: ^3.3.3+1
  google_sign_in: ^5.0.2
  image_picker: ^0.8.4+1
  image_cropper: ^1.4.1
  cached_network_image: ^3.1.0
  get_storage: ^2.0.3

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

